### ISSUE TITLE
Support nullable enums

### ISSUE THREAD

**Issue by voxpelli** [reinfi/openapi-models#56]
Another thing I ran into when I tried converting a large complex OpenAPI definition (https://github.com/reinfi/openapi-models/pull/55) was that it didn't like the `null` values that one are [required to use in nullable enums](https://swagger.io/docs/specification/v3_0/data-models/enums/#nullable-enums):

```yaml
type: string
nullable: true  # <---
enum:
  - asc
  - desc
  - null        # <--- without quotes, i.e. null not "null"
```

It probably relates to the challenges of https://github.com/reinfi/openapi-models/pull/55 where `null` is not an acceptable PHP identifier and as such I guess one maybe needs to add a similar workaround and do eg:

```php
if ($enumCaseName === null) {
    $enumCaseName = 'NULL';
}
```
